### ISSUE TITLE
Make script for extract individual face image to a folder 

### ISSUE THREAD

**Issue by mozarik** [mozarik/bangkit-capstone-CAP0166#27]
Let say I have 
![image](https://user-images.githubusercontent.com/39885486/119248992-c1d85b80-bbc7-11eb-8f7d-f37d3c7b68d6.png)

Bisa di extract dan di save gk individual image tersebut kedalam sebuah folder let say the folder name is "extracted_images"
each faces file_name let say "face_0", "face_1", and so on

**Comment by YusrilHasanuddin** [comment]
Please refer to my push here: [https://github.com/mozarik/bangkit-capstone-CAP0166/tree/develop/ml-project/face_detect_and_extract](url)

**Comment by YusrilHasanuddin** [comment]
You can run this script without worrying about the same name exist folder because this script will generate a new folder every time you run it.
Please pay attention to detect_face.py line 6, it must be as same as the path of this folder .xml. Also, in line 35-42 it must adjust the as the user computer.
I tried it using as default path as I can, but it always returns an error, so please if you can solve this problem. 

Oh, one more thing, this script still returns an error even it is already satisfied with the goal of this method. Suggestion: I think there is a problem with closing cv2.

Run using: python detect_face.py [IMAGE-PATH]. If you are still confused, I enclosed a picture of how to run this file.

Sincerely,
@mozarik

**Comment by mozarik** [comment]
Ok will check it

**Comment by mozarik** [comment]
why we need the XML file ? @YusrilHasanuddin

**Comment by YusrilHasanuddin** [comment]
To locate the face

**Comment by mozarik** [comment]
We can use MTCNN for easy convenience. please refer to my `playground_zein.ipynb`

**Comment by mozarik** [comment]
i'm updating my `playground_zein.ipynb` to getting things clear. 11674af44774b1868ef10550050737e58c9e6411 @YusrilHasanuddin

**Comment by YusrilHasanuddin** [comment]
So I thought you ask me to create a method to extract faces wkwk, 
Please check on my playground. then copy the last cell to your last cell playground.

**Comment by mozarik** [comment]
Getting this error. what open CV2 library you use ? 
![image](https://user-images.githubusercontent.com/39885486/119264563-5073c980-bc16-11eb-8e44-e360af1ba17e.png)

run cv2.__version__ 

![image](https://user-images.githubusercontent.com/39885486/119264609-7dc07780-bc16-11eb-9aa5-e7296e61e353.png)

**Comment by mozarik** [comment]
btw can you separate the code for saving the image and to visualize the image extracted ?

**Comment by YusrilHasanuddin** [comment]
Ok wait...

**Comment by mozarik** [comment]
> Getting this error. what open CV2 library you use ?
> ![image](https://user-images.githubusercontent.com/39885486/119264563-5073c980-bc16-11eb-8e44-e360af1ba17e.png)
> 
> run cv2.**version**
> 
> ![image](https://user-images.githubusercontent.com/39885486/119264609-7dc07780-bc16-11eb-9aa5-e7296e61e353.png)

This problem is solved

**Comment by mozarik** [comment]
script yang ada di `playground_yusril.ipynb` is ok... 

but we need to make one python.py script to run on the terminal 

Make a script based on `playground_yusril.ipynb` but without the visualitation that take argument on the command line `--image_path="many_faces.jpg" --output_path="extracted_face"`

@YusrilHasanuddin

**Comment by YusrilHasanuddin** [comment]
Okay

**Comment by mozarik** [comment]
> Okay

You may want to take a look at this https://docs.python.org/3/library/argparse.html

**Comment by YusrilHasanuddin** [comment]
Try my new commit
parameter:
[YOUR_PYTHON_.EXE] detect_extract_save.py [YOUR_IMAGE_PATH]
Example:
C:\Programs\Python38\python.exe detect_extract_save.py C:\User\People.jpg

**Comment by mozarik** [comment]
Ok im checkin it out

**Comment by mozarik** [comment]
This kind work fb6d877c6dbabeeea9defffa72858746ecfbeb45 but the image is not RGB 
![image](https://user-images.githubusercontent.com/39885486/119266871-16f38c00-bc1f-11eb-8b53-01784683e7fc.png)

**Comment by YusrilHasanuddin** [comment]
I updated on first method, then I creating save method using matplotlib, please check on my new pussh

**Comment by mozarik** [comment]
> I updated on first method, then I creating save method using matplotlib, please check on my new pussh

Check this commit ... on `playground_zein.ipynb` 11674af44774b1868ef10550050737e58c9e6411 @YusrilHasanuddin . see the last cell . can you make the script by changing the save method ?

**Comment by mozarik** [comment]
This commit solve this issue 98d11e2bcdd256a8c9368a4cd2a71c3b20d032e1

Thank you @YusrilHasanuddin
