### ISSUE TITLE
Face Embedding and Face Classifier Process 

### ISSUE THREAD

**Issue by mozarik** [mozarik/bangkit-capstone-CAP0166#30]
So extracting face is done so the next step is Face Embedding and Face Classifier.

Hi Yusril can we learn about this [Face Embedding and Classifier](https://machinelearningmastery.com/how-to-develop-a-face-recognition-system-using-facenet-in-keras-and-an-svm-classifier/)

The way they save the embedding to a .npz file is kinda nice to have in our apps. We may want to borrow their code for our project. I'm gonna learn this tonight. Tomorrow i have to prepare and test covid for my Travel to Surabaya 

@YusrilHasanuddin 

Thank you

**Comment by mozarik** [comment]
See this commit cfbb2ab @YusrilHasanuddin . take a look at `predict.ipynb` file. Going to sleep now

**Comment by YusrilHasanuddin** [comment]
Sorry, zein, I just read this issue. I am very sorry I will check it tomorrow because today, I want to go to Malang.

**Comment by mozarik** [comment]
Welp i guess both of us will go to Malang

**Comment by mozarik** [comment]
Welp i guess the inference time took 5 minute. 😢😢😢
