### ISSUE TITLE
Render json file response after invoking /getresults

### ISSUE THREAD

**Issue by mozarik** [mozarik/bangkit-capstone-CAP0166#41]
The json response structure look like this 

```json
{
  "status": 200,
  "data": [
    {
      "name": "Zein",
      "percentage": "0.95",
      "url_image_face": "https://storage.googleapis.com/the-watcher-storage-file/d4181961f6c7aa0c94f9100eb859621c"
    },
    {
      "name": "Zein",
      "percentage": "0.95",
      "url_image_face": "https://storage.googleapis.com/the-watcher-storage-file/d4181961f6c7aa0c94f9100eb859621c"
    },
    {
      "name": "Zein",
      "percentage": "0.95",
      "url_image_face": "https://storage.googleapis.com/the-watcher-storage-file/d4181961f6c7aa0c94f9100eb859621c"
    },
    {
      "name": "Zein",
      "percentage": "0.95",
      "url_image_face": "https://storage.googleapis.com/the-watcher-storage-file/d4181961f6c7aa0c94f9100eb859621c"
    }
  ]
}
```

Maybe the you guys can mock this up to complete this issue.

**Comment by antonikurniawan** [comment]
![image](https://user-images.githubusercontent.com/72740154/120215998-a7a21b80-c260-11eb-9194-862fa577ab3d.png)
untuk bagian percentagenya udah di buat, dan nama parameter/variable buat ambil datanya udah di sesuaikan (dalam mockup)

**Comment by mozarik** [comment]
Ok untuk file image apakah bisa di mock up dulu ? jadi kalian ngambil direct link url image dari internet lalu kalian jadiin url di `"url_image_face"`

**Comment by mozarik** [comment]
Klo udah di commit mungki bisa di refer commit hash nya disini ...

**Comment by antonikurniawan** [comment]
> Ok untuk file image apakah bisa di mock up dulu ? jadi kalian ngambil direct link url image dari internet lalu kalian jadiin url di `"url_image_face"`

untuk mock imagenya bisa ambil dari link foto di internet

**Comment by antonikurniawan** [comment]
> Klo udah di commit mungki bisa di refer commit hash nya disini ...

mikirnya ini mau jadiin upload dulu baru commit

**Comment by mozarik** [comment]
> > Ok untuk file image apakah bisa di mock up dulu ? jadi kalian ngambil direct link url image dari internet lalu kalian jadiin url di `"url_image_face"`
> 
> untuk mock imagenya bisa ambil dari link foto di internet

Bisa kok

**Comment by mozarik** [comment]
Good job android team thank you
