### ISSUE TITLE
Please upload the web version of this up in github, don't forget to documentate it....

### ISSUE THREAD

**Issue by YusrilHasanuddin** [mozarik/bangkit-capstone-CAP0166#46]

**Comment by salshafrhdba** [comment]
![image](https://user-images.githubusercontent.com/79617311/120376179-c1695e80-c345-11eb-8e4e-1b2cc3235700.png)

Am I doing right? Make a simple upload file

**Comment by salshafrhdba** [comment]
![image](https://user-images.githubusercontent.com/79617311/120376622-4eacb300-c346-11eb-93cb-44a6f73859f2.png)

Am I doing right? just for simple upload file

**Comment by salshafrhdba** [comment]
![image](https://user-images.githubusercontent.com/79617311/120377327-2ec9bf00-c347-11eb-89b3-abe029aaf82d.png)

Am I doing right? just for simple upload file

**Comment by mozarik** [comment]
Push it on branch based on yusril instruction. maybe make new folder on root project . called front-end-web

**Comment by mozarik** [comment]
This #53 Resolve this issue
